name: TinyProtocolAPI
main: com.gmail.zahusek.tinyprotocolapi.TinyProtocolAPI
version: 4.6 (ActionBar Update)
authors: [ZahuseK, ElDzi]
website: https://www.spigotmc.org/resources/tinyprotocolapi.9787/
description: TinyProtocolAPI - your small library.
commands:
    tinyprotocolapi:
        description: Command for test
